### ISSUE TITLE
请帮忙解答此代码不能正常编译问题

### ISSUE THREAD

**Issue by kindcao** [yizenghui/wxspider#2]
环境：

go sdk ：1.12
gcc：gcc version 5.1.0 (tdm64-1)

编译错误信息：

# command-line-arguments
run\wxspider.go:65:14: g.bot.Excute undefined (type *wechat.WeChat has no field or method Excute)
run\wxspider.go:146:14: undefined: wechat.AwakenNewBot
run\wxspider.go:174:32: data.GGID undefined (type wechat.EventContactData has no field or method GGID)

备注：
本人对go语言了解不多，请帮忙解答一下，感谢！

**Comment by kindcao** [comment]
go sdk: 1.8.6

# github.com/jinzhu/gorm
..\src\github.com\jinzhu\gorm\main.go:25: undefined: sync.Map

**Comment by yizenghui** [comment]
问题已经重现，安排三天内处理。

**Comment by yizenghui** [comment]
github.com/Kevingong2013/wechat  更新了接口，已同步更新。

**Comment by kindcao** [comment]
多谢回复，问题已解决。
